package api

func (h *Handler) routes() {
	h.mux.HandleFunc("GET /", h.dashboard)
	h.mux.HandleFunc("GET /healthz", h.health)
	h.mux.HandleFunc("GET /api/boreholes", h.listBoreholes)
	h.mux.HandleFunc("POST /api/boreholes", h.createBorehole)
	h.mux.HandleFunc("GET /api/boreholes/{id}", h.getBorehole)
	h.mux.HandleFunc("POST /api/boreholes/{id}/archive", h.archiveBorehole)
	h.mux.HandleFunc("GET /api/boreholes/{id}/snapshot", h.snapshot)
	h.mux.HandleFunc("GET /api/boreholes/{id}/alerts", h.alerts)
	h.mux.HandleFunc("GET /api/probes", h.listProbes)
	h.mux.HandleFunc("POST /api/probes", h.registerProbe)
	h.mux.HandleFunc("POST /api/probes/{id}/remove", h.removeProbe)
	h.mux.HandleFunc("POST /api/scans", h.startScan)
	h.mux.HandleFunc("GET /api/scans/{id}", h.getScan)
	h.mux.HandleFunc("GET /api/scans", h.listScans)
	h.mux.HandleFunc("POST /api/scans/{id}/seal", h.sealScan)
	h.mux.HandleFunc("POST /api/readings", h.recordReading)
	h.mux.HandleFunc("POST /api/readings/batch", h.recordReadings)
	h.mux.HandleFunc("POST /api/calibrations", h.recordCalibration)
	h.mux.HandleFunc("POST /api/scans/{id}/profile", h.rebuildProfile)
	h.mux.HandleFunc("POST /api/scans/{id}/assess", h.assessScan)
	h.mux.HandleFunc("GET /api/scans/{id}/diagnostics", h.diagnostics)
	h.mux.HandleFunc("POST /api/scans/{id}/release", h.prepareRelease)
	h.mux.HandleFunc("POST /api/scans/{id}/publish", h.publishRelease)
	h.mux.HandleFunc("GET /api/scans/{id}/manifest", h.manifest)
	h.mux.HandleFunc("GET /api/reports/daily", h.dailyReport)
}
